---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
os:
  - linux
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec rake spec
